// Real content for brent_the_programmer.
// Brent just started painting — 1 WIP (Diana) and a pile of printed 1:6 figures
// awaiting paint. Status values: "wip" (actively painting) | "pile" (printed).
// Globals: GALLERY, POSTS, NOW_PROJECTS, SOCIALS, FACTIONS.

const FACTIONS = [
  { id: "all",     label: "All" },
  { id: "dnd",     label: "D&D Cartoon" },
  { id: "comics",  label: "Comics & Heroes" },
  { id: "anime",   label: "Anime" },
  { id: "scifi",   label: "Sci-Fi & Film" },
];

// Every entry is a 1:6 figure. `image` is the WIP shot (or absent if not
// photographed yet — Placeholder falls back to the striped block).
const GALLERY = [
  {
    id: "diana",
    title: "Diana the Acrobat",
    faction: "dnd",
    factionLabel: "D&D Cartoon · Toon Studios",
    status: "wip",
    stage: "base coats started",
    designer: "Toon Studios",
    image: "assets/gallery/diana.jpg",
    notes: "My first model. A realistic / stylized take on Diana from the 1983 D&D animated series. Skin base coats in. Going slow on purpose — every step is a first for me.",
    size: "wide",
    placeholder: "wip · diana, base coats in progress",
  },
  {
    id: "bobby",
    title: "Bobby the Barbarian & Uni",
    faction: "dnd",
    factionLabel: "D&D Cartoon · Toon Studios",
    status: "pile",
    stage: "in the pile · printed",
    designer: "Toon Studios",
    image: "assets/gallery/bobby.jpg",
    notes: "Bobby with his unicorn Uni. Goes with Diana, Hank, Eric, and Sheila — the goal is to eventually have all five together.",
    size: "1",
    placeholder: "pile · bobby & uni, printed",
  },
  {
    id: "hank",
    title: "Hank the Ranger",
    faction: "dnd",
    factionLabel: "D&D Cartoon · Toon Studios",
    status: "pile",
    stage: "assembled, based & primed",
    designer: "Toon Studios",
    image: "assets/gallery/hank-web.jpg",
    notes: "Cartoon set member. Cleaned, pinned to his rocky base, and primed — ready for paint. The bow is going to want a steadier hand than I currently have.",
    size: "tall",
    placeholder: "pile · hank ranger, primed",
  },
  {
    id: "eric",
    title: "Eric the Cavalier",
    faction: "dnd",
    factionLabel: "D&D Cartoon · Toon Studios",
    status: "pile",
    stage: "in the pile · printed",
    designer: "Toon Studios",
    image: "assets/gallery/eric.jpg",
    notes: "Cartoon set member. That shield is begging for some kind of heraldry.",
    size: "1",
    placeholder: "pile · eric cavalier, printed",
  },
  {
    id: "sheila",
    title: "Sheila the Thief",
    faction: "dnd",
    factionLabel: "D&D Cartoon · Toon Studios",
    status: "pile",
    stage: "in the pile · printed",
    designer: "Toon Studios",
    image: "assets/gallery/sheila.jpg",
    notes: "Cartoon set member. The hooded cloak hides a lot of the model — should be a good one to push value contrast on.",
    size: "small",
    placeholder: "pile · sheila thief, printed",
  },
  {
    id: "spiderman",
    title: "Spider-Man",
    faction: "comics",
    factionLabel: "Comics · Groundeffected",
    status: "pile",
    stage: "in the pile · printed & assembled",
    designer: "Groundeffected",
    image: "assets/gallery/spiderman.jpg",
    notes: "A big perched-on-the-signpost diorama — Spidey crouched on the Columbus Ave / One Way signs over a brownstone facade. This one's for my grandson Colton. No pressure at all.",
    size: "1",
    placeholder: "pile · spider-man diorama, printed",
  },
  {
    id: "batgirl-66",
    title: "Batgirl (1966)",
    faction: "comics",
    factionLabel: "Comics · BrunoArt3D",
    status: "pile",
    stage: "in the pile · printed",
    designer: "BrunoArt3D",
    image: "assets/gallery/batgirl-66.jpg",
    notes: "The 1966 TV Batgirl. Printed in a peach + purple resin combo — looks oddly painterly already.",
    size: "tall",
    placeholder: "pile · 1966 batgirl, printed",
  },
  {
    id: "drax",
    title: "Drax the Destroyer (MCU)",
    faction: "comics",
    factionLabel: "Comics · Wicked 3D",
    status: "pile",
    stage: "in the pile · printed",
    designer: "Wicked 3D",
    image: "assets/gallery/drax.jpg",
    notes: "All those scarification tattoos are going to be a study in their own right. Not next, but soon.",
    size: "2",
    placeholder: "pile · drax, printed",
  },
  {
    id: "homelander",
    title: "Homelander",
    faction: "comics",
    factionLabel: "Comics · Zenith Studios",
    status: "pile",
    stage: "in the pile · printed",
    designer: "Zenith Studios",
    image: "assets/gallery/homelander.jpg",
    notes: "From The Boys. The cape and quilted texture are going to be the focal point — clean enough that there's nowhere for sloppy paint to hide.",
    size: "1",
    placeholder: "pile · homelander, printed",
  },
  {
    id: "soldier-boy",
    title: "Soldier Boy",
    faction: "comics",
    factionLabel: "Comics · Zenith Studios",
    status: "pile",
    stage: "in the pile · printed",
    designer: "Zenith Studios",
    image: "assets/gallery/soldier-boy.jpg",
    notes: "Also from The Boys. Tactical gear with all the strap detail. Probably an army-painter approach to start — recess shade and dry brush.",
    size: "2",
    placeholder: "pile · soldier boy, printed",
  },
  {
    id: "peacemaker",
    title: "Peacemaker",
    faction: "comics",
    factionLabel: "Comics · ZEZ Studios",
    status: "pile",
    stage: "in the pile · printed",
    designer: "ZEZ Studios",
    image: "assets/gallery/peacemaker.jpg",
    notes: "The chrome helmet is going to require committing to true metallic vs. NMM. No idea which yet.",
    size: "2",
    placeholder: "pile · peacemaker, printed",
  },
  {
    id: "cassie-hack",
    title: "Cassie Hack",
    faction: "comics",
    factionLabel: "Comics · MCM3D",
    status: "pile",
    stage: "in the pile",
    designer: "MCM3D",
    notes: "From the Hack/Slash comics. Going to be moody — high-contrast lighting, lots of blacks and reds.",
    size: "tall",
    placeholder: "pile · cassie hack",
  },
  {
    id: "captain-america",
    title: "Captain America",
    faction: "comics",
    factionLabel: "Comics · Wicked 3D",
    status: "pile",
    stage: "in the pile",
    designer: "Wicked 3D",
    notes: "Patriotic palette, clean lines. Sounds simple, will not be.",
    size: "1",
    placeholder: "pile · captain america",
  },
  {
    id: "kenshin",
    title: "Himura Kenshin",
    faction: "anime",
    factionLabel: "Anime · CA3D Studios",
    status: "pile",
    stage: "in the pile",
    designer: "CA3D Studios",
    image: "assets/gallery/kenshin-web.jpg",
    notes: "Rurouni Kenshin. The cross-scar on his cheek is going to be the test of whether my freehand is ready.",
    size: "tall",
    placeholder: "pile · kenshin",
  },
  {
    id: "faye",
    title: "Faye Valentine",
    faction: "anime",
    factionLabel: "Anime · CA3D Studios",
    status: "pile",
    stage: "in the pile · printed",
    designer: "CA3D Studios",
    image: "assets/gallery/faye.jpg",
    notes: "Cowboy Bebop. Skin tones at scale are intimidating — definitely not a starter project.",
    size: "1",
    placeholder: "pile · faye valentine, printed",
  },
  {
    id: "spike",
    title: "Spike Spiegel",
    faction: "anime",
    factionLabel: "Anime · CA3D Studios",
    status: "pile",
    stage: "in the pile · printed & assembled",
    designer: "CA3D Studios",
    image: "assets/gallery/spike-web.jpg",
    notes: "Cowboy Bebop. Couldn't resist this one \u2014 Spike mid-draw, jacket flaring, cigarette in hand, perched on a chunk of rubble with spent shell casings. Whoever I am that day, see you, space cowboy.",
    size: "tall",
    placeholder: "pile · spike spiegel, printed",
  },
  {
    id: "kitsune-miku",
    title: "Kitsune Miku",
    faction: "anime",
    factionLabel: "Anime · Abe3d",
    status: "pile",
    stage: "in the pile",
    designer: "Abe3d",
    notes: "Hatsune Miku in kitsune (fox) styling. Vibrant palette — should be a fun one once the basics feel less wobbly.",
    size: "small",
    placeholder: "pile · kitsune miku",
  },
  {
    id: "robocop",
    title: "Robocop",
    faction: "scifi",
    factionLabel: "Sci-Fi · CA3D Studios",
    status: "pile",
    stage: "in the pile · printed",
    designer: "CA3D Studios",
    image: "assets/gallery/robocop.jpg",
    notes: "Two-tone resin print — Robocop in gray, takedown victim in flesh. Going to want to learn metallics properly before this one.",
    size: "1",
    placeholder: "pile · robocop, printed",
  },
  {
    id: "freddy",
    title: "Freddy Krueger",
    faction: "scifi",
    factionLabel: "Sci-Fi · Wicked 3D",
    status: "pile",
    stage: "in the pile · printed",
    designer: "Wicked 3D",
    image: "assets/gallery/freddy.jpg",
    notes: "A Nightmare on Elm Street. The base has a little manhole-cover detail — texture work is going to be the whole game on this one.",
    size: "tall",
    placeholder: "pile · freddy krueger, printed",
  },
  {
    id: "sister-of-battle",
    title: "Sister of Battle",
    faction: "scifi",
    factionLabel: "Sci-Fi · Warhammer 40K · BrunoArt3D",
    status: "pile",
    stage: "in the pile · printed",
    designer: "BrunoArt3D",
    image: "assets/gallery/sister-of-battle.jpg",
    notes: "Adepta Sororitas at 1:6 — armor plates everywhere, every panel an opportunity for a freehand sigil. Long-term goal piece.",
    size: "tall",
    placeholder: "pile · sister of battle, printed",
  },
];

// Blog: section is real. These are DRAFT SEEDS — title + excerpt only.
// Brent might write any of them, none of them, or use them as jumping-off
// points. Empty body[] means PostPage shows the "coming soon" treatment.
const POSTS = [
  {
    id: "its-not-personal-its-pem",
    title: "It's Not Personal. It's PEM.",
    cat: "Caregiving",
    date: "June 2026",
    read: "4 min",
    excerpt: "One of the hardest lessons I've learned as a caregiver: sometimes the person you love isn't really themselves. Sometimes it's the crash speaking for them — and knowing the difference can change everything.",
    body: [
      "One of the hardest lessons I've had to learn as a caregiver is that sometimes the person you love isn't really themselves.",
      "If you're caring for someone with ME/CFS, you've probably seen it happen.",
      "Maybe they had a good day. Maybe they pushed a little too hard because they wanted to feel normal again. Maybe they attended a family gathering, ran an errand, worked on a hobby, or simply spent more energy than their body could afford.",
      "Then the crash comes.",
      "The symptoms get worse. The exhaustion becomes overwhelming. The pain increases. Brain fog settles in like a heavy storm cloud.",
      "And sometimes, so does irritability.",
      "Words become sharper. Patience disappears. Small frustrations become big ones. Conversations that would normally be harmless suddenly turn into arguments.",
      "And if you're the caregiver standing there trying to help, it can feel personal. It can feel like you're being blamed. It can feel like you're being attacked by the very person you're sacrificing so much to support.",
      "I've been there. More times than I can count.",
      "The difficult truth is that in many of those moments, the problem isn't me.",
      "The problem is PEM.",
      "When someone is experiencing Post-Exertional Malaise, their body is under immense stress. They're often dealing with levels of exhaustion that healthy people simply don't have a frame of reference for. Imagine trying to navigate your worst flu, severe sleep deprivation, chronic pain, and sensory overload all at once.",
      "Now imagine trying to remain patient and emotionally balanced while carrying that burden.",
      "That doesn't make hurtful words okay. It doesn't mean boundaries shouldn't exist. But it does mean that understanding what's happening can change how we respond.",
      "## Am I talking to my loved one, or to PEM?",
      "I've had to learn to pause and ask myself a simple question:",
      "> Am I talking to my loved one right now, or am I talking to PEM?",
      "Sometimes the answer is obvious.",
      "The person I know \u2014 the kind, thoughtful, caring person \u2014 is still there. They're just buried under symptoms they didn't ask for and can't control.",
      "That realization doesn't magically make hurt feelings disappear. It doesn't make difficult conversations easier. But it helps me avoid turning a temporary crash into a lasting wound.",
      "It reminds me not to build resentment around moments that neither of us would have chosen.",
      "Most importantly, it reminds me that we are on the same side.",
      "The illness is the problem. PEM is the problem. Not the person.",
      "Even after years of caregiving, I still have to remind myself of this. Some lessons aren't learned once. They're practiced over and over again. And this is one of them.",
      "## If you're a caregiver having one of those days",
      "So if you're a caregiver and you're in the middle of one of those difficult days, I want you to know something:",
      "You're not failing. You're not weak for feeling hurt. You're not wrong for struggling.",
      "But before you carry those words with you, take a moment to consider where they came from.",
      "Sometimes the person you love is speaking. And sometimes it's the crash speaking for them.",
      "Knowing the difference can change everything.",
      "~~signoff",
    ],
    tags: ["caregiving", "me/cfs", "PEM"],
    placeholder: "essay · a quiet moment at the end of a hard day",
  },
  {
    id: "still-getting-set-up",
    title: "Still Getting Set Up",
    cat: "Studio Notes",
    date: "June 2026",
    read: "3 min",
    excerpt: "There's a funny part of starting something new that nobody really talks about — the part before the thing looks like a thing. That's where I'm at right now.",
    body: [
      "There's a funny part of starting something new that nobody really talks about.",
      "The part before the thing looks like a thing.",
      "That's where I'm at right now.",
      "The hobby desk is slowly coming together. The printers are running. Paints are getting organized. I'm figuring out photography, experimenting with recording, moving lights around, adjusting camera angles, and trying to make the workspace feel less like \u201Ca pile of gear and half-finished ideas\u201D and more like a place I can create and actually share from.",
      "It's progress.",
      "Just not the dramatic kind.",
      "A lot of this season has looked like test prints, reorganizing supplies, trying a paint setup one way and then changing it again, learning what works, and figuring out how to build something sustainable around real life.",
      "And real life definitely still happens here.",
      "Work. Caregiving. Appointments. Energy shifts.",
      "The unexpected stuff that doesn't care what plans were on the calendar.",
      "## Taking my time",
      "That's part of why I'm taking my time.",
      "I don't want this to feel rushed.",
      "I don't want it to become another thing to grind through or another box to check.",
      "I want it to feel creative. Grounded. Sustainable.",
      "Something I genuinely enjoy and can share honestly.",
      "## The behind-the-scenes version",
      "So if you've found your way here early \u2014 welcome.",
      "You're catching the behind-the-scenes version. The setup. The experiments. The occasional mess. The learning curve. The \u201Cwhy are there twelve cords under this desk and where does this one even go?\u201D phase.",
      "And honestly\u2026 I kind of like that.",
      "Because there's something real about beginnings.",
      "Things don't have to be polished before they matter. They don't have to be finished before they're worth sharing.",
      "Sometimes showing up while things are still in progress matters just as much.",
      "## The next thing in front of me",
      "Thanks for being here while I get things dialed in.",
      "More painting, more printing, and more projects are on the way.",
      "For now I'm just doing the next thing in front of me.",
      "Trusting the process. Taking care of myself. And moving forward one brushstroke at a time.",
      "~~signoff",
    ],
    tags: ["studio", "behind the scenes", "self-care"],
    placeholder: "essay · the desk mid-setup, cords everywhere",
  },
  {
    id: "burnout",
    title: "When Burnout Starts Burning Everything Down",
    cat: "Self-Care",
    date: "May 2026",
    read: "5 min",
    excerpt: "People talk about burnout like it always looks like exhaustion. Mine looked messier than that. On survival mode, therapy, and how sitting down to paint one small thing helped me find my way back.",
    body: [
      "People talk about burnout like it always looks like exhaustion.",
      "Like being tired. Like needing a nap. Like taking a weekend off and bouncing back.",
      "That wasn't my experience.",
      "For me, burnout looked a lot messier.",
      "It looked like running on empty for too long and then making decisions I knew weren't helping. Trying to feel better quickly. Trying to feel anything besides overwhelmed.",
      "Trying to get through another hard day without really stopping long enough to ask what the cost was becoming.",
      "## When it turns destructive",
      "And over time that kind of burnout can turn destructive.",
      "You stop taking care of yourself. You avoid things. You make choices that feel good for five minutes and harder for five months.",
      "You tell yourself you'll fix it later.",
      "You push through because people need you.",
      "And eventually you wake up and realize \u201Cpushing through\u201D has turned into survival mode — and survival mode has been driving for a while.",
      "That was hard to admit.",
      "Especially when you care deeply about your family. Especially when you're trying to be dependable. Especially when the people you love need so much from you and you feel like you should be able to carry it.",
      "## What helped",
      "Therapy helped me name some things I had spent a long time trying to outrun.",
      "Self-care stopped feeling optional. It stopped being \u201Cnice if I can find the time.\u201D",
      "It became part of staying functional. Part of staying present. Part of staying me.",
      "## And then, painting",
      "And oddly enough\u2026 painting helped too.",
      "Sitting down with a miniature or a figure gave me something simple and honest to focus on.",
      "No fixing everything. No solving every problem. No carrying the whole weight of the week.",
      "Just the next brushstroke. The next layer.",
      "The reminder that ugly middle stages are normal. That progress doesn't always look dramatic. That patience matters. That rebuilding takes time. That you can start where you are.",
      "## The next right thing",
      "If you're burned out and things feel heavier than they should\u2026 if you've been coping in ways you wish you weren't\u2026 if you feel like you've drifted farther from yourself than you meant to \u2014",
      "You are not alone.",
      "You don't have to fix everything today. You don't have to become a different person overnight.",
      "Sometimes the next right thing is smaller than you think.",
      "Drink some water. Answer one email. Sit outside for five minutes. Paint one small thing. Take one honest breath. Ask for help.",
      "Then do the next thing after that.",
      "That counts. More than you know.",
      "~~signoff",
    ],
    tags: ["self-care", "caregiving", "burnout"],
    placeholder: "essay · wet palette, half-finished mini",
  },
];

// "On the desk" — only Diana for now.
const NOW_PROJECTS = [
  {
    id: "diana",
    title: "Diana the Acrobat",
    cat: "1:6 figure · Toon Studios",
    desc: "My first model. Currently working through base coats. Going one thin layer at a time and resisting the urge to rush.",
    pct: 15,
    eta: "No deadline · learning as I go",
    stages: ["print", "clean", "assemble", "primer", "base coats", "shade", "highlight", "details", "varnish"],
    current: 4,
    pile: ["just figuring it out"],
    placeholder: "now · diana wip",
    image: "assets/gallery/diana.jpg",
  },
];

const SOCIALS = [
  { id: "youtube",   label: "YouTube",   handle: "@brent_the_programmer", desc: "Long-form paint-alongs and quiet workbench sessions.", url: "https://www.youtube.com/channel/UC0nUK7GE2y4qYskGsXiTh9g" },
  { id: "instagram", label: "Instagram", handle: "@brent_the_programmer", desc: "Final shots and the occasional WIP.", url: "https://instagram.com/brent_the_programmer" },
  { id: "facebook",  label: "Facebook",  handle: "Brenttheprogrammer",    desc: "Where my family looks at the figures.", url: "https://facebook.com/Brenttheprogrammer" },
  { id: "patreon",   label: "Patreon",   handle: "Brent Stephenson",      desc: "Support the bench — early looks and works in progress.", url: "https://www.patreon.com/c/BrentStephenson" },
  { id: "coffee",    label: "Buy Me a Coffee", handle: "brent_the_programmer", desc: "A one-off thank-you, if a piece or a post helped your day.", url: "https://buymeacoffee.com/brent_the_programmer" },
  { id: "discord",   label: "Discord",    handle: "the bench",             desc: "A quiet little server — paint talk, WIPs, and good company.", url: "https://discord.gg/u7K5Zuvc" },
];

Object.assign(window, { FACTIONS, GALLERY, POSTS, NOW_PROJECTS, SOCIALS });
