// Real content for brent_the_programmer.
// Brent just started painting — 2 WIP (Diana, Hank) and a pile of printed 1:6 figures
// awaiting paint. Status values: "wip" (actively painting) | "pile" (printed).
// Globals: GALLERY, POSTS, NOW_PROJECTS, SOCIALS, FACTIONS.

const FACTIONS = [
  { id: "all",     label: "All" },
  { id: "dnd",     label: "D&D Cartoon" },
  { id: "comics",  label: "Comics & Heroes" },
  { id: "anime",   label: "Anime" },
  { id: "scifi",   label: "Sci-Fi & Film" },
];

// Every entry is a 1:6 figure. `image` is the WIP shot (or absent if not
// photographed yet — Placeholder falls back to the striped block).
const GALLERY = [
  {
    id: "diana",
    title: "Diana the Acrobat",
    faction: "dnd",
    factionLabel: "D&D Cartoon · Toon Studios",
    status: "wip",
    stage: "on the gold details · portrait & base to go",
    designer: "Toon Studios",
    image: "assets/gallery/diana-web.jpg",
    notes: "My first model. A realistic / stylized take on Diana from the 1983 D&D animated series. Skin, hair, and fur are in; I'm working through the gold details now, with her portrait and base still to go. Slow, but she's turning out well \u2014 and gold, it turns out, is the fussiest paint there is.",
    size: "wide",
    placeholder: "wip · diana, base coats in progress",
  },
  {
    id: "bobby",
    title: "Bobby the Barbarian & Uni",
    faction: "dnd",
    factionLabel: "D&D Cartoon · Toon Studios",
    status: "pile",
    stage: "in the pile · printed",
    designer: "Toon Studios",
    image: "assets/gallery/bobby.jpg",
    notes: "Bobby with his unicorn Uni. Goes with Diana, Hank, Eric, and Sheila — the goal is to eventually have all five together.",
    size: "1",
    placeholder: "pile · bobby & uni, printed",
  },
  {
    id: "hank",
    title: "Hank the Ranger",
    faction: "dnd",
    factionLabel: "D&D Cartoon · Toon Studios",
    status: "wip",
    stage: "waist armor wash · forearm, bow & quiver to go",
    designer: "Toon Studios",
    image: "assets/gallery/hank-wip-web.jpg",
    notes: "Hank's coming along nicely. Still need a brown wash on the waist armor to bring out the leather, some spots left on the base, and his right forearm, bow, and quiver still to paint.",
    size: "tall",
    placeholder: "wip · hank ranger, bust in progress",
  },
  {
    id: "eric",
    title: "Eric the Cavalier",
    faction: "dnd",
    factionLabel: "D&D Cartoon · Toon Studios",
    status: "pile",
    stage: "in the pile · printed",
    designer: "Toon Studios",
    image: "assets/gallery/eric.jpg",
    notes: "Cartoon set member. That shield is begging for some kind of heraldry.",
    size: "1",
    placeholder: "pile · eric cavalier, printed",
  },
  {
    id: "sheila",
    title: "Sheila the Thief",
    faction: "dnd",
    factionLabel: "D&D Cartoon · Toon Studios",
    status: "pile",
    stage: "in the pile · printed",
    designer: "Toon Studios",
    image: "assets/gallery/sheila.jpg",
    notes: "Cartoon set member. The hooded cloak hides a lot of the model — should be a good one to push value contrast on.",
    size: "small",
    placeholder: "pile · sheila thief, printed",
  },
  {
    id: "spiderman",
    title: "Spider-Man",
    faction: "comics",
    factionLabel: "Comics · Groundeffected",
    status: "pile",
    stage: "in the pile · printed & assembled",
    designer: "Groundeffected",
    image: "assets/gallery/spiderman.jpg",
    notes: "A big perched-on-the-signpost diorama — Spidey crouched on the Columbus Ave / One Way signs over a brownstone facade. This one's for my grandson Colton. No pressure at all.",
    size: "1",
    placeholder: "pile · spider-man diorama, printed",
  },
  {
    id: "batgirl-66",
    title: "Batgirl (1966)",
    faction: "comics",
    factionLabel: "Comics · BrunoArt3D",
    status: "pile",
    stage: "in the pile · printed",
    designer: "BrunoArt3D",
    image: "assets/gallery/batgirl-66.jpg",
    notes: "The 1966 TV Batgirl. Printed in a peach + purple resin combo — looks oddly painterly already.",
    size: "tall",
    placeholder: "pile · 1966 batgirl, printed",
  },
  {
    id: "drax",
    title: "Drax the Destroyer (MCU)",
    faction: "comics",
    factionLabel: "Comics · Wicked 3D",
    status: "pile",
    stage: "in the pile · printed",
    designer: "Wicked 3D",
    image: "assets/gallery/drax.jpg",
    notes: "All those scarification tattoos are going to be a study in their own right. Not next, but soon.",
    size: "2",
    placeholder: "pile · drax, printed",
  },
  {
    id: "homelander",
    title: "Homelander",
    faction: "comics",
    factionLabel: "Comics · Zenith Studios",
    status: "pile",
    stage: "in the pile · printed",
    designer: "Zenith Studios",
    image: "assets/gallery/homelander.jpg",
    notes: "From The Boys. The cape and quilted texture are going to be the focal point — clean enough that there's nowhere for sloppy paint to hide.",
    size: "1",
    placeholder: "pile · homelander, printed",
  },
  {
    id: "billy-butcher",
    title: "Billy Butcher",
    faction: "comics",
    factionLabel: "Comics · Zenith Studios",
    status: "pile",
    stage: "in the pile · printed",
    designer: "Zenith Studios (@zenith_studios_)",
    image: "assets/gallery/billy-butcher.jpg",
    notes: "From The Boys \u2014 trench coat, pineapple shirt, and Terror the bulldog at his feet. The long coat and folds should be a good excuse to practice fabric shading.",
    size: "1",
    placeholder: "pile \u00b7 billy butcher, printed",
  },
  {
    id: "soldier-boy",
    title: "Soldier Boy",
    faction: "comics",
    factionLabel: "Comics · Zenith Studios",
    status: "pile",
    stage: "in the pile · printed",
    designer: "Zenith Studios",
    image: "assets/gallery/soldier-boy.jpg",
    notes: "Also from The Boys. Tactical gear with all the strap detail. Probably an army-painter approach to start — recess shade and dry brush.",
    size: "2",
    placeholder: "pile · soldier boy, printed",
  },
  {
    id: "peacemaker",
    title: "Peacemaker",
    faction: "comics",
    factionLabel: "Comics · ZEZ Studios",
    status: "pile",
    stage: "in the pile · printed",
    designer: "ZEZ Studios",
    image: "assets/gallery/peacemaker.jpg",
    notes: "The chrome helmet is going to require committing to true metallic vs. NMM. No idea which yet.",
    size: "2",
    placeholder: "pile · peacemaker, printed",
  },
  {
    id: "cassie-hack",
    title: "Cassie Hack",
    faction: "comics",
    factionLabel: "Comics · MCM3D",
    status: "pile",
    stage: "in the pile",
    designer: "MCM3D",
    notes: "From the Hack/Slash comics. Going to be moody — high-contrast lighting, lots of blacks and reds.",
    size: "tall",
    placeholder: "pile · cassie hack",
  },
  {
    id: "captain-america",
    title: "Captain America",
    faction: "comics",
    factionLabel: "Comics · Wicked 3D",
    status: "pile",
    stage: "in the pile",
    designer: "Wicked 3D",
    notes: "Patriotic palette, clean lines. Sounds simple, will not be.",
    size: "1",
    placeholder: "pile · captain america",
  },
  {
    id: "kenshin",
    title: "Himura Kenshin",
    faction: "anime",
    factionLabel: "Anime · CA3D Studios",
    status: "pile",
    stage: "in the pile",
    designer: "CA3D Studios",
    image: "assets/gallery/kenshin-web.jpg",
    notes: "Rurouni Kenshin. The cross-scar on his cheek is going to be the test of whether my freehand is ready.",
    size: "tall",
    placeholder: "pile · kenshin",
  },
  {
    id: "faye",
    title: "Faye Valentine",
    faction: "anime",
    factionLabel: "Anime · CA3D Studios",
    status: "pile",
    stage: "in the pile · printed",
    designer: "CA3D Studios",
    image: "assets/gallery/faye.jpg",
    notes: "Cowboy Bebop. Skin tones at scale are intimidating — definitely not a starter project.",
    size: "1",
    placeholder: "pile · faye valentine, printed",
  },
  {
    id: "spike",
    title: "Spike Spiegel",
    faction: "anime",
    factionLabel: "Anime · CA3D Studios",
    status: "pile",
    stage: "in the pile · printed & assembled",
    designer: "CA3D Studios",
    image: "assets/gallery/spike-web.jpg",
    notes: "Cowboy Bebop. Couldn't resist this one \u2014 Spike mid-draw, jacket flaring, cigarette in hand, perched on a chunk of rubble with spent shell casings. Whoever I am that day, see you, space cowboy.",
    size: "tall",
    placeholder: "pile · spike spiegel, printed",
  },
  {
    id: "kitsune-miku",
    title: "Kitsune Miku",
    faction: "anime",
    factionLabel: "Anime · Abe3d",
    status: "pile",
    stage: "in the pile",
    designer: "Abe3d",
    notes: "Hatsune Miku in kitsune (fox) styling. Vibrant palette — should be a fun one once the basics feel less wobbly.",
    size: "small",
    placeholder: "pile · kitsune miku",
  },
  {
    id: "robocop",
    title: "Robocop",
    faction: "scifi",
    factionLabel: "Sci-Fi · CA3D Studios",
    status: "pile",
    stage: "in the pile · printed",
    designer: "CA3D Studios",
    image: "assets/gallery/robocop.jpg",
    notes: "Two-tone resin print — Robocop in gray, takedown victim in flesh. Going to want to learn metallics properly before this one.",
    size: "1",
    placeholder: "pile · robocop, printed",
  },
  {
    id: "freddy",
    title: "Freddy Krueger",
    faction: "scifi",
    factionLabel: "Sci-Fi · Wicked 3D",
    status: "pile",
    stage: "in the pile · printed",
    designer: "Wicked 3D",
    image: "assets/gallery/freddy.jpg",
    notes: "A Nightmare on Elm Street. The base has a little manhole-cover detail — texture work is going to be the whole game on this one.",
    size: "tall",
    placeholder: "pile · freddy krueger, printed",
  },
  {
    id: "sister-of-battle",
    title: "Sister of Battle",
    faction: "scifi",
    factionLabel: "Sci-Fi · Warhammer 40K · BrunoArt3D",
    status: "pile",
    stage: "in the pile · printed",
    designer: "BrunoArt3D",
    image: "assets/gallery/sister-of-battle.jpg",
    notes: "Adepta Sororitas at 1:6 — armor plates everywhere, every panel an opportunity for a freehand sigil. Long-term goal piece.",
    size: "tall",
    placeholder: "pile · sister of battle, printed",
  },
];

// Blog: section is real. These are DRAFT SEEDS — title + excerpt only.
// Brent might write any of them, none of them, or use them as jumping-off
// points. Empty body[] means PostPage shows the "coming soon" treatment.
const POSTS = [
  {
    id: "every-research-breakthrough",
    title: "Every Research Breakthrough Is Another Reason to Keep Hope Alive",
    cat: "ME/CFS",
    date: "July 2026",
    read: "6 min",
    excerpt: "On celebrating ME/CFS research progress without expecting miracles \u2014 a biomarker study, repurposed treatments, and mitochondrial research, and what hope without hype looks like for caregivers.",
    body: [
      "If you live with ME/CFS\u2014or care for someone who does\u2014you've probably developed a complicated relationship with research announcements.",
      "Every few months there's another headline. Another study. Another promising treatment. Another scientist saying they're getting closer to understanding what causes this devastating illness.",
      "After years of waiting, it's understandable to become skeptical.",
      "As a caregiver, I've learned to celebrate progress without expecting miracles. Hope is important, but so is managing expectations. The two aren't opposites\u2014they're partners.",
      "This week, Solve M.E. shared several exciting updates that reminded me why continuing to support research matters so much.",
      "## A New Biomarker Study",
      "Researchers at Simmaron Research have published a new Solve-funded study in the Journal of Translational Medicine. While I'll leave the detailed scientific analysis to the researchers themselves, what stands out to me isn't just another paper being published.",
      "It's another piece of the puzzle.",
      "For decades, people with ME/CFS have been told their symptoms were anxiety, depression, or simply being out of shape. Every well-designed study that identifies measurable biological differences chips away at those outdated misconceptions.",
      "Science doesn't move in giant leaps very often.",
      "It moves one carefully validated discovery at a time.",
      "## Repurposing Existing Treatments",
      "Another topic that caught my attention was a webinar discussing rapamycin as a potential treatment for ME/CFS.",
      "One of the most encouraging aspects of modern medical research is the growing focus on repurposing existing medications. Instead of starting from scratch with drugs that could take a decade or more to develop, researchers are investigating medicines that already have established safety profiles.",
      "That doesn't mean rapamycin is \u201Cthe answer.\u201D",
      "It means scientists have identified enough evidence to justify asking the question.",
      "And that's exactly how good science works.",
      "## Looking at Mitochondria",
      "Another upcoming study focuses on IVO-21, a therapy designed to stabilize mitochondria\u2014the tiny power plants inside nearly every cell in our bodies.",
      "Anyone familiar with ME/CFS knows that energy production has long been one of the leading areas of investigation. When your body's ability to generate energy is impaired, everyday activities become overwhelming. Walking to the mailbox. Taking a shower. Holding a conversation.",
      "Researchers are continuing to explore whether improving mitochondrial function could reduce some of those debilitating symptoms.",
      "Again, this isn't a cure announcement.",
      "It's another carefully chosen path worth exploring.",
      "## Why This Matters to Caregivers",
      "Research updates like these don't immediately change our day-to-day lives.",
      "Tomorrow morning my wife will still wake up with ME/CFS.",
      "My son will still have to carefully ration his energy to avoid post-exertional malaise.",
      "We'll still plan our days around energy envelopes instead of calendars.",
      "But something has changed.",
      "There are more scientists asking better questions.",
      "There are more organizations funding meaningful research.",
      "There are more clinical trials than there were just a few years ago.",
      "That's progress.",
      "## Hope Without Hype",
      "One thing I've learned is that false hope can be just as painful as having no hope at all.",
      "Every new study deserves excitement\u2014but it also deserves patience.",
      "Science is deliberately slow because it has to be. Researchers must verify results, repeat experiments, challenge assumptions, and ensure treatments are both safe and effective before they can become standard care.",
      "That process can feel agonizingly slow when someone you love is suffering.",
      "But it's also what makes genuine breakthroughs trustworthy.",
      "## We Keep Going",
      "Caregiving often feels like living in the space between \u201Cnot yet\u201D and \u201Cmaybe someday.\u201D",
      "It's easy to focus on everything that hasn't happened.",
      "Sometimes it's worth remembering everything that has.",
      "Ten years ago, ME/CFS received only a fraction of the attention it receives today. More researchers are entering the field. More funding is becoming available. More patients are being heard. More caregivers have communities that understand what they're facing.",
      "None of that removes today's challenges.",
      "But it reminds me that progress is real.",
      "So I'll keep reading the studies.",
      "I'll keep cheering for the researchers.",
      "I'll keep hoping\u2014carefully, realistically, and intentionally.",
      "Because every published paper, every clinical trial, and every scientist choosing to dedicate their career to ME/CFS brings us one step closer to answers.",
      "And for families like mine, that's worth celebrating.",
      "If you or someone you love is living with ME/CFS, I encourage you to follow organizations like Solve M.E. that continue to fund research and provide educational resources. Staying informed doesn't change today's reality, but it does remind us that we're not standing still.",
      "~~signoff",
    ],
    tags: ["me/cfs", "caregiving", "research"],
    placeholder: "essay \u00b7 research & hope",
    image: "assets/posts/every-research-breakthrough-web.jpg",
  },
  {
    id: "stl-studio-release",
    title: "STL Studio: Finally Making Sense of My 3D Print Library",
    cat: "Side Project",
    date: "July 2026",
    read: "6 min",
    excerpt: "A free, open-source app I built for organizing, browsing, and managing a huge 3D-printable model library \u2014 variant grouping, metadata enrichment, and AI-assisted painting guides built around your own paint shelf.",
    body: [
      "If you're anything like me, your STL collection probably started with \"just a few models.\"",
      "Then came another Kickstarter. Then Patreon. Then MMF sales. Then that creator who makes amazing goblins. Before you know it, you've got thousands of files scattered across dozens of folders, duplicate downloads, multiple scales of the same miniature, and absolutely no idea where that one dragon you know you own actually lives.",
      "I built STL Studio because I got tired of fighting my file system instead of printing and painting miniatures.",
      "If it solves the same problem for you, I'd love for you to give it a try.",
      "## What is STL Studio?",
      "STL Studio is a free, open-source application for organizing, browsing, and managing large collections of 3D-printable models.",
      "Point it at your library and it'll do the heavy lifting \u2014 scanning your folders, identifying related models, enriching them with metadata, and presenting everything in a clean, searchable library.",
      "There's a native Windows desktop application built with Electron, and if you're on Linux or macOS, you can run exactly the same application through Docker with a browser-based interface.",
      "![STL Studio library view, grid of One Page Rules miniatures](assets/posts/stl-studio-1-web.jpg)",
      "## What can it do?",
      "Smart Library Scanning \u2014 no matter how many creators you've collected from, or how inconsistent their folder structures are, STL Studio scans your library and builds a unified catalog. No reorganizing required.",
      "Intelligent Variant Grouping \u2014 this is the feature that started the entire project. STL Studio recognizes when multiple files represent the same miniature or object \u2014 different scales, poses, pre-supported versions, weapon options, and more \u2014 and groups them together automatically. Unlike simple folder-based grouping, it uses multiple signals from filenames and folder context to make smart decisions. Don't like the automatic grouping? Merge groups, split them apart, or customize the behavior for individual folders.",
      "![Variant group view showing two AH Druzhak variants side by side](assets/posts/stl-studio-2-web.jpg)",
      "Automatic Metadata Enrichment \u2014 once your library is scanned, STL Studio extracts useful information like creator, character, scale, categories, and other details from filenames and folder structures. The result is a library that's actually searchable instead of relying on your memory of where something was downloaded three years ago.",
      "A Real Library \u2014 instead of digging through endless folders, browse your collection visually. Search by name, filter by creator, browse by scale or category, and rediscover models you forgot you owned. Honestly, that last one happens to me more often than I'd like to admit.",
      "![Model detail page with file info and location](assets/posts/stl-studio-3-web.jpg)",
      "AI-Assisted Painting Guides \u2014 this is probably my favorite feature. Choose a model, tell STL Studio which paints you actually own, and it will generate a step-by-step painting guide tailored to your paint collection. Instead of recommending twenty paints you've never heard of, it builds recipes using what's already sitting on your hobby desk, complete with layering suggestions, highlights, shadows, and technique notes.",
      "![Paint Shelf view listing owned paints by code and line](assets/posts/stl-studio-4-web.jpg)",
      "Built Around Your Workflow \u2014 every hobbyist organizes files differently. Rather than forcing everyone into one workflow, STL Studio is highly configurable. Features like folder-based grouping are optional, allowing the application to adapt to your existing organization instead of making you rebuild your entire library from scratch.",
      "## Why I built it",
      "I was managing thousands of STL files across dozens of creators and realized there really wasn't a tool built specifically for this hobby.",
      "Windows Explorer doesn't understand that four files are really the same goblin with different weapon loadouts. Spreadsheets become impossible to maintain. Generic asset managers don't understand miniatures.",
      "So I built the tool I wished I'd had years ago.",
      "## Where to find it",
      "STL Studio is completely free and open source. You can find the project on GitHub: [github.com/RBStephenson/STL-Studio](https://github.com/RBStephenson/STL-Studio)",
      "If you're on Windows, grab the latest installer from the Releases page. If you're using Linux or macOS, clone the repository and run docker compose up to launch the browser-based version.",
      "And if you're a developer, feel free to dive into the code. Bug reports, feature requests, and pull requests are always welcome.",
      "Whether you're printing tabletop miniatures, display pieces, terrain, cosplay props, or just have an STL collection that's gotten a little out of hand, I hope STL Studio helps you spend less time hunting for files and more time doing what we actually enjoy: printing, painting, and creating.",
      "> Trust the process. Take care of yourself. One brushstroke at a time.",
      "~~signoff",
    ],
    tags: ["stl studio", "side project", "open source"],
    image: "assets/posts/stl-studio-1-web.jpg",
    placeholder: "release \u00b7 stl studio library screenshot",
    externalLink: "https://github.com/RBStephenson/STL-Studio",
  },
  {
    id: "hank-progress-update",
    title: "Hank Progress Update: Leather, Bowstrings, and Getting There",
    cat: "On the Bench",
    date: "July 2026",
    read: "3 min",
    excerpt: "My first real 1:6 figure is starting to look like a ranger instead of a pile of primer. A quick check-in on where Hank stands \u2014 and what's still left on the pile.",
    body: [
      "Hank's coming along nicely.",
      "This is my first real go at a 1:6 figure. No test piece this time \u2014 I'm painting straight onto the model, which has been equal parts nerve-wracking and satisfying.",
      "The green hood and tunic are holding their layers well. The bust reads the way I wanted it to. Little by little, this is starting to look like a person instead of a collection of base coats.",
      "## What's left",
      "I still need a brown wash on his waist armor to make it a little more leather-like \u2014 right now it reads a bit flat, and a wash should bring out the texture and give it some age.",
      "There are still a few spots left to paint on the base.",
      "And I haven't touched his right forearm, his bow, or his quiver yet. Those are next.",
      "![Hank the Ranger, front view, waist armor and base still to finish](assets/gallery/hank-wip-web.jpg)",
      "![Hank the Ranger, three-quarter view](assets/posts/hank-progress-2-web.jpg)",
      "![Hank the Ranger, close-up on the bust and hood](assets/posts/hank-progress-3-web.jpg)",
      "## Slow and steady",
      "I don't have a deadline on this one, which has honestly made it more enjoyable. There's no rush to get Hank finished by a certain date \u2014 just steady progress, a little at a time, whenever I can sit down at the table.",
      "That's the pace I'm trying to keep with most things these days.",
      "More updates soon as the forearm, bow, and quiver come together.",
      "> Trust the process. Take care of yourself. One brushstroke at a time.",
      "~~signoff",
    ],
    tags: ["wip", "hank", "1:6 figure"],
    image: "assets/gallery/hank-wip-web.jpg",
    placeholder: "wip \u00b7 hank ranger, waist armor and base left",
  },
  {
    id: "pay-the-bills-first",
    title: "Pay the Bills First: A Lesson in Moderation",
    cat: "Self-Care",
    date: "July 2026",
    read: "4 min",
    excerpt: "Self-care can become avoidance if we're not careful. On the difference between recharging and escaping \u2014 and the simple question I ask myself before I let myself paint.",
    body: [
      "One of the hardest lessons I've had to learn as a caregiver has nothing to do with medications, doctor's appointments, or learning about chronic illness.",
      "It's about moderation.",
      "If you've followed me for any length of time, you've probably heard me talk about the importance of self-care. I genuinely believe it's essential. You cannot continually pour from an empty cup. We all need time to recharge, whether that's painting a miniature, playing a game, reading a book, or simply sitting quietly for a little while.",
      "But I've also learned something equally important.",
      "Self-care can become avoidance if we're not careful.",
      "There have been days where I've thought, \u201CI'll just paint for an hour.\u201D Before I know it, that hour becomes three. The sink is still full of dishes. The laundry is still sitting in the dryer. The floors still need vacuuming. None of the things I knew needed to be done have magically disappeared.",
      "Instead of feeling refreshed, I start feeling guilty.",
      "That guilt slowly turns into anxiety.",
      "Every unfinished chore becomes another reminder that I'm falling behind.",
      "Ironically, the very activity that was supposed to help me relax now becomes harder to enjoy because I can't stop thinking about everything waiting for me when I put the brush down.",
      "That's when I realized something.",
      "Before I spend time on myself, I need to pay the bills first.",
      "I'm not talking about the electric bill or the mortgage.",
      "I'm talking about the daily responsibilities that keep life moving.",
      "Wash the dishes.",
      "Start the laundry.",
      "Vacuum the living room.",
      "Take out the trash.",
      "Answer the email you've been putting off.",
      "Do the things that genuinely need to get done first.",
      "## Not everything \u2014 just enough",
      "Notice I didn't say everything.",
      "That's an impossible standard, especially as a caregiver. There will always be another chore waiting. There will always be another project you could start. If we wait until everything is perfect before taking a break, we'll never take one.",
      "Instead, I try to ask myself a simple question:",
      "\u201CHave I done enough today that I can enjoy my hobby without feeling guilty?\u201D",
      "If the answer is yes, then I paint.",
      "And here's the surprising part.",
      "I enjoy it more.",
      "The miniature doesn't feel like I'm escaping my responsibilities. It feels like a reward for taking care of them.",
      "The anxiety is quieter.",
      "The guilt isn't sitting in the back of my mind.",
      "I'm actually present in the moment instead of mentally making a to-do list between brushstrokes.",
      "## A healthy rhythm",
      "Moderation is difficult because both extremes can feel justified.",
      "If we work constantly, we burn out.",
      "If we rest constantly, life begins to pile up around us.",
      "Somewhere between those two is a healthy rhythm.",
      "Take care of your responsibilities.",
      "Then take care of yourself.",
      "Neither one should come at the expense of the other.",
      "You deserve the chance to recharge. But you also deserve the peace of sitting down at your hobby table knowing you've already handled what truly mattered today.",
      "Sometimes the best form of self-care isn't escaping your responsibilities.",
      "Sometimes it's doing just enough of them that your heart and mind are free to rest.",
      "> Trust the process. Take care of yourself. One brushstroke at a time.",
      "~~signoff",
    ],
    tags: ["caregiving", "self-care", "moderation"],
    image: "assets/posts/pay-the-bills-first-web.jpg",
    placeholder: "essay \u00b7 dish rack and a half-painted brush",
  },
  {
    id: "print-failures-and-laundry",
    title: "Print Failures, Laundry, and the Stories We Tell Ourselves",
    cat: "Caregiving",
    date: "June 2026",
    read: "5 min",
    excerpt: "A week of failed prints and a forgotten load of laundry sent me straight to the same verdict: my fault. On the difference between learning from failure and blaming yourself for it \u2014 and the grace we extend to everyone except ourselves.",
    body: [
      "As caregivers, we can become very good at spotting problems.",
      "Sometimes we're a little too good at it.",
      "This week I had several 3D printing failures while working on a large model. Each failure felt like a punch to the gut. Resin wasted. Time lost. Progress stalled.",
      "My immediate reaction was the same after every failed print:",
      "\u201CI must have messed up the supports.\u201D",
      "So I adjusted things. I second-guessed myself. I replayed every decision I'd made.",
      "After the latest failure, I finally sat down and really examined what was happening.",
      "The failures weren't occurring where I expected. Looking closer, I found multiple suction cups in the model. The creator's original orientation \u2014 an orientation I had used rather than my own \u2014 was likely contributing to the problem.",
      "Was it entirely my fault?",
      "Probably not.",
      "Could I learn something from it?",
      "Absolutely.",
      "But there was a difference between learning from the failure and blaming myself for it.",
      "Around the same time, I found myself doing something very similar in my life as a caregiver.",
      "I forgot to finish the laundry.",
      "My wife ended up taking care of it.",
      "Immediately, I started beating myself up.",
      "You forgot.",
      "You should have done better.",
      "You're letting people down.",
      "If you're a caregiver, those thoughts may sound familiar.",
      "## The verdict we rush to",
      "We carry a lot of responsibility. We manage appointments, medications, meals, finances, household chores, work obligations, and a thousand tiny tasks that nobody else sees.",
      "The problem is that after carrying responsibility for long enough, we start believing we are responsible for everything.",
      "When something goes wrong, we skip the investigation and go straight to the verdict.",
      "Guilty.",
      "The print failed? Your fault.",
      "The laundry wasn't finished? Your fault.",
      "Someone had a bad day? Your fault.",
      "The house isn't perfect? Your fault.",
      "But reality is rarely that simple.",
      "Sometimes the print fails because of suction forces you didn't see.",
      "Sometimes you're exhausted.",
      "Sometimes there simply aren't enough hours in the day.",
      "Sometimes the people you love help carry the load because that's what families do.",
      "A print failure doesn't mean you're a bad hobbyist.",
      "An unfinished chore doesn't mean you're a bad caregiver.",
      "A difficult day doesn't erase the hundreds of things you got right that nobody noticed.",
      "## The grace we keep for everyone else",
      "What I've been trying to learn \u2014 and honestly, I'm still learning it \u2014 is to pause before assigning blame.",
      "Investigate first.",
      "Would I judge another caregiver this harshly?",
      "Would I tell a friend they were a failure because they forgot to finish the laundry?",
      "Would I look at a failed print and immediately conclude the hobbyist was incompetent?",
      "Of course not.",
      "Yet somehow we often extend grace to everyone except ourselves.",
      "The truth is that neither caregiving nor 3D printing is about perfection.",
      "Both involve trial and error.",
      "Both involve setbacks.",
      "Both require patience.",
      "And both require the willingness to try again after something falls apart.",
      "The next print is already sliced and waiting.",
      "The laundry got finished.",
      "The world didn't end.",
      "Maybe that's the lesson.",
      "> Not every failure is actually failure. Sometimes it's just information. Sometimes it's just life. And sometimes the story we're telling ourselves is far harsher than the reality we're living.",
      "~~signoff",
    ],
    tags: ["caregiving", "3d printing", "self-care"],
    image: "assets/posts/print-failures-and-laundry-web.jpg",
    placeholder: "essay \u00b7 a failed resin print on the bench",
  },
  {
    id: "weight-of-a-good-day",
    title: "The Weight of a Good Day",
    cat: "Caregiving",
    date: "June 2026",
    read: "5 min",
    excerpt: "Father's Day was wonderful \u2014 and if you're a caregiver, you probably already know why that sentence makes me uncomfortable. On guilt, the math we do before every outing, and remembering that caring goes both directions.",
    body: [
      "Father's Day was wonderful.",
      "And if you're a caregiver, you probably already know why that sentence makes me uncomfortable.",
      "The morning started the way many special occasions do in our house. My wife and son asked what I wanted to do for Father's Day. I told them I'd like to visit our local game store.",
      "It's something my son and I have always enjoyed when he's feeling up to it. My wife had never been, and I thought she might enjoy seeing that part of our world too.",
      "But from the moment the idea left my mouth, the guilt started creeping in.",
      "\u201CAre you sure you're up for it?\u201D",
      "\u201CWe don't have to go.\u201D",
      "\u201CIt's okay if you'd rather stay home.\u201D",
      "\u201CI don't want you to push yourselves because of me.\u201D",
      "I must have offered them an escape route a dozen times before we ever got in the car.",
      "## The math caregivers do",
      "Caregivers become experts at calculating costs.",
      "Every outing has a price. Every activity has consequences. Every decision gets weighed against symptoms, energy reserves, recovery time, and the possibility of post-exertional malaise waiting around the corner.",
      "Eventually, you start doing the math automatically.",
      "You stop asking, \u201CWould this be fun?\u201D and start asking, \u201CIs it worth the crash?\u201D",
      "The problem is that special days don't escape that calculation. Birthdays. Anniversaries. Father's Day. They all come with a hidden question:",
      "> How much suffering am I asking someone I love to endure so that I can have a good day?",
      "That's a difficult question to carry.",
      "The thing is, my wife and son didn't just tolerate the outing. They enjoyed it.",
      "We wandered through the game store. We looked at things that caught our attention. We shared conversations. We laughed.",
      "Afterward, we went to dinner at a place I knew my son would actually enjoy eating at.",
      "For a few hours, we weren't focused on illness. We weren't focused on limitations. We were just a family spending time together.",
      "It was exactly the kind of day I had hoped for.",
      "Then came the familiar reminder that nothing is ever quite that simple.",
      "When we got home, my son said he needed to lie down before watching our nightly show. We had done a lot that day.",
      "By the time we got settled, it was getting late. I still had work the next morning. I needed to take my medication and head to bed.",
      "The show didn't happen.",
      "And as I write this, I don't know what today will look like for either of them. Maybe they'll be okay. Maybe they'll be paying for yesterday's adventure. Maybe the recovery will take days.",
      "That's the reality of living with chronic illness. Sometimes you don't know the bill until after you've already enjoyed the experience.",
      "And that's where the guilt tries to move in. It whispers that maybe I shouldn't have asked. Maybe I shouldn't have wanted anything. Maybe Father's Day should have been smaller. Maybe staying home would have been safer.",
      "## The gift we forget",
      "But I've been learning something over the years. People who love us deserve the right to make their own choices.",
      "My wife and son understood the risks better than anyone. They know their bodies. They know the potential consequences. And despite all of that, they chose to spend that energy with me.",
      "Not because they had to. Not because I pressured them. Not because it was expected. Because they wanted to.",
      "That's the part caregivers often forget. We spend so much time protecting the people we love that we accidentally take away their ability to give. We forget that caring goes both directions.",
      "Sometimes the greatest gift isn't protecting someone from every possible hardship. Sometimes it's allowing them to share an experience, create a memory, and decide for themselves that the joy was worth the cost.",
      "I don't know what today will bring. I don't know how much recovery yesterday may require. What I do know is this:",
      "I had a wonderful Father's Day. Not because we went to a game store. Not because we went out to dinner. Not because everything went perfectly.",
      "I had a wonderful Father's Day because my family chose to spend part of their limited energy with me. That's a gift I will never take for granted.",
      "And maybe that's the lesson.",
      "> Caregiver guilt tells us to measure every moment by its cost. Love teaches us to remember its value. Sometimes both things can be true at the same time.",
      "~~signoff",
    ],
    tags: ["caregiving", "me/cfs", "guilt"],
    image: "assets/posts/weight-of-a-good-day-web.jpg",
    placeholder: "essay \u00b7 the local game store, Father's Day",
  },
  {
    id: "was-it-worth-it",
    title: "Was It Worth It?",
    cat: "Caregiving",
    date: "June 2026",
    read: "4 min",
    excerpt: "This weekend we took a history boat tour as a family \u2014 laughter, sunshine, a few hours that weren't about illness. Then the crash came. On PEM, the cost of making memories, and the question every caregiver eventually has to ask.",
    body: [
      "This weekend, my family and I took a history boat tour in Wilmington, North Carolina. The tour focused on the history behind Outlander and the impact Scottish settlers had on the region. It was fascinating, educational, and honestly, a lot of fun.",
      "We laughed. We learned. We spent time together.",
      "For a few hours, we weren't thinking about doctor's appointments, symptoms, limitations, or what tomorrow might look like.",
      "We were just a family making memories.",
      "But caregiving has a way of making even the happiest moments complicated.",
      "It was hot. Not as hot as it was supposed to be, thankfully, but still hot. We had to find public parking and walk several blocks to and from the boat. By the time we got home, I could already see the signs.",
      "The slower movements.",
      "The fatigue.",
      "The pain.",
      "The careful calculations of how much energy was left in the tank.",
      "My son looked at me and said it would probably be Tuesday before he felt normal again.",
      "That's the reality of living with illnesses that involve Post-Exertional Malaise (PEM). Activities that most people would consider minor can trigger days of recovery. Sometimes the crash doesn't even arrive until later. Sometimes it sneaks up on you. Sometimes it hits like a freight train.",
      "As a caregiver, those are the moments that make me question everything.",
      "## Was it worth it?",
      "Was a few hours of fun worth days of pain?",
      "Was a boat ride worth the exhaustion that follows?",
      "Was the memory worth the cost?",
      "The truth is, I don't know if there is a perfect answer.",
      "What I do know is that life cannot become nothing more than symptom management.",
      "If every decision is made solely to avoid discomfort, eventually the illness takes more than physical ability. It begins taking experiences. Adventures. Memories. Connection.",
      "It starts taking life itself.",
      "That doesn't mean we ignore consequences. It doesn't mean we push beyond limits recklessly. It doesn't mean we pretend the suffering isn't real.",
      "The suffering is real.",
      "The recovery is real.",
      "The pain is real.",
      "But so was watching my family enjoy themselves.",
      "So was hearing them talk about the history they learned.",
      "So was sharing something together that wasn't centered around illness.",
      "As caregivers, we often carry the weight of these decisions. We watch the aftermath. We help pick up the pieces. We sit beside the people we love while they recover. And sometimes we wonder if we made the wrong choice.",
      "## A better question",
      "Maybe the better question isn't \u201CWas it worth it?\u201D",
      "Maybe the better question is:",
      "> Did we spend our limited energy on something meaningful?",
      "This weekend, I think we did.",
      "The next few days may be difficult. There may be pain, fatigue, frustration, and recovery.",
      "But there will also be a memory of a boat ride on the Cape Fear River, stories from history, shared laughter, and time spent together as a family.",
      "And sometimes that's the balance we have to strike.",
      "Not between good and bad.",
      "Not between right and wrong.",
      "But between protecting life and living it.",
      "That's a difficult lesson for caregivers.",
      "It's one I'm still learning.",
      "~~signoff",
    ],
    tags: ["caregiving", "me/cfs", "PEM"],
    placeholder: "essay · the Cape Fear River from the boat, late afternoon",
  },
  {
    id: "diana-and-the-gold",
    title: "Diana, and the Trouble with Gold",
    cat: "Studio Notes",
    date: "June 2026",
    read: "2 min",
    excerpt: "A progress update on my first model. Skin, hair, and fur are done, and she's actually turning out well. Now I'm on the gold details — and I have learned that painting gold sucks.",
    image: "assets/gallery/diana-web.jpg",
    body: [
      "Quick update on Diana — my very first model.",
      "Skin, hair, and fur are done. She's standing there on one leg, mid-pose, and honestly? She's turning out well. Better than I expected when I started.",
      "I want to be clear about something, because I think it matters: I'm not the fastest painter. I'm not the most talented one either. But I'm learning, and I'm having fun, and right now that's exactly enough.",
      "## What's left",
      "Right now I'm working through the gold details — the cuffs, the armbands, the collar. After that it's just her portrait and the base, and she's finished.",
      "Which brings me to the one lesson I did not expect to learn on my first model.",
      "## Painting gold sucks",
      "I mean it. Metallics are their own kind of difficult. The flakes pool in ways flat colors never do, the coverage is streaky, every brushstroke wants to show, and the way it catches light means a spot that looked perfect under my desk lamp looks completely different the second I move the figure.",
      "I've redone the same little cuff more times than I'd like to admit.",
      "But that's kind of the whole point of a first model, isn't it? You find the thing that's hard, and you do it badly, and then you do it a little less badly, and eventually it's just a thing you know how to do.",
      "Diana's not done. But she's close, and I'm proud of her — streaky gold and all.",
      "~~signoff",
    ],
    tags: ["studio", "diana", "wip"],
    placeholder: "studio · diana, on the gold",
  },
  {
    id: "its-not-personal-its-pem",
    title: "It's Not Personal. It's PEM.",
    cat: "Caregiving",
    date: "June 2026",
    read: "4 min",
    excerpt: "One of the hardest lessons I've learned as a caregiver: sometimes the person you love isn't really themselves. Sometimes it's the crash speaking for them — and knowing the difference can change everything.",
    body: [
      "One of the hardest lessons I've had to learn as a caregiver is that sometimes the person you love isn't really themselves.",
      "If you're caring for someone with ME/CFS, you've probably seen it happen.",
      "Maybe they had a good day. Maybe they pushed a little too hard because they wanted to feel normal again. Maybe they attended a family gathering, ran an errand, worked on a hobby, or simply spent more energy than their body could afford.",
      "Then the crash comes.",
      "The symptoms get worse. The exhaustion becomes overwhelming. The pain increases. Brain fog settles in like a heavy storm cloud.",
      "And sometimes, so does irritability.",
      "Words become sharper. Patience disappears. Small frustrations become big ones. Conversations that would normally be harmless suddenly turn into arguments.",
      "And if you're the caregiver standing there trying to help, it can feel personal. It can feel like you're being blamed. It can feel like you're being attacked by the very person you're sacrificing so much to support.",
      "I've been there. More times than I can count.",
      "The difficult truth is that in many of those moments, the problem isn't me.",
      "The problem is PEM.",
      "When someone is experiencing Post-Exertional Malaise, their body is under immense stress. They're often dealing with levels of exhaustion that healthy people simply don't have a frame of reference for. Imagine trying to navigate your worst flu, severe sleep deprivation, chronic pain, and sensory overload all at once.",
      "Now imagine trying to remain patient and emotionally balanced while carrying that burden.",
      "That doesn't make hurtful words okay. It doesn't mean boundaries shouldn't exist. But it does mean that understanding what's happening can change how we respond.",
      "## Am I talking to my loved one, or to PEM?",
      "I've had to learn to pause and ask myself a simple question:",
      "> Am I talking to my loved one right now, or am I talking to PEM?",
      "Sometimes the answer is obvious.",
      "The person I know \u2014 the kind, thoughtful, caring person \u2014 is still there. They're just buried under symptoms they didn't ask for and can't control.",
      "That realization doesn't magically make hurt feelings disappear. It doesn't make difficult conversations easier. But it helps me avoid turning a temporary crash into a lasting wound.",
      "It reminds me not to build resentment around moments that neither of us would have chosen.",
      "Most importantly, it reminds me that we are on the same side.",
      "The illness is the problem. PEM is the problem. Not the person.",
      "Even after years of caregiving, I still have to remind myself of this. Some lessons aren't learned once. They're practiced over and over again. And this is one of them.",
      "## If you're a caregiver having one of those days",
      "So if you're a caregiver and you're in the middle of one of those difficult days, I want you to know something:",
      "You're not failing. You're not weak for feeling hurt. You're not wrong for struggling.",
      "But before you carry those words with you, take a moment to consider where they came from.",
      "Sometimes the person you love is speaking. And sometimes it's the crash speaking for them.",
      "Knowing the difference can change everything.",
      "~~signoff",
    ],
    tags: ["caregiving", "me/cfs", "PEM"],
    placeholder: "essay · a quiet moment at the end of a hard day",
  },
  {
    id: "still-getting-set-up",
    title: "Still Getting Set Up",
    cat: "Studio Notes",
    date: "June 2026",
    read: "3 min",
    excerpt: "There's a funny part of starting something new that nobody really talks about — the part before the thing looks like a thing. That's where I'm at right now.",
    body: [
      "There's a funny part of starting something new that nobody really talks about.",
      "The part before the thing looks like a thing.",
      "That's where I'm at right now.",
      "The hobby desk is slowly coming together. The printers are running. Paints are getting organized. I'm figuring out photography, experimenting with recording, moving lights around, adjusting camera angles, and trying to make the workspace feel less like \u201Ca pile of gear and half-finished ideas\u201D and more like a place I can create and actually share from.",
      "It's progress.",
      "Just not the dramatic kind.",
      "A lot of this season has looked like test prints, reorganizing supplies, trying a paint setup one way and then changing it again, learning what works, and figuring out how to build something sustainable around real life.",
      "And real life definitely still happens here.",
      "Work. Caregiving. Appointments. Energy shifts.",
      "The unexpected stuff that doesn't care what plans were on the calendar.",
      "## Taking my time",
      "That's part of why I'm taking my time.",
      "I don't want this to feel rushed.",
      "I don't want it to become another thing to grind through or another box to check.",
      "I want it to feel creative. Grounded. Sustainable.",
      "Something I genuinely enjoy and can share honestly.",
      "## The behind-the-scenes version",
      "So if you've found your way here early \u2014 welcome.",
      "You're catching the behind-the-scenes version. The setup. The experiments. The occasional mess. The learning curve. The \u201Cwhy are there twelve cords under this desk and where does this one even go?\u201D phase.",
      "And honestly\u2026 I kind of like that.",
      "Because there's something real about beginnings.",
      "Things don't have to be polished before they matter. They don't have to be finished before they're worth sharing.",
      "Sometimes showing up while things are still in progress matters just as much.",
      "## The next thing in front of me",
      "Thanks for being here while I get things dialed in.",
      "More painting, more printing, and more projects are on the way.",
      "For now I'm just doing the next thing in front of me.",
      "Trusting the process. Taking care of myself. And moving forward one brushstroke at a time.",
      "~~signoff",
    ],
    tags: ["studio", "behind the scenes", "self-care"],
    placeholder: "essay · the desk mid-setup, cords everywhere",
  },
  {
    id: "burnout",
    title: "When Burnout Starts Burning Everything Down",
    cat: "Self-Care",
    date: "May 2026",
    read: "5 min",
    excerpt: "People talk about burnout like it always looks like exhaustion. Mine looked messier than that. On survival mode, therapy, and how sitting down to paint one small thing helped me find my way back.",
    body: [
      "People talk about burnout like it always looks like exhaustion.",
      "Like being tired. Like needing a nap. Like taking a weekend off and bouncing back.",
      "That wasn't my experience.",
      "For me, burnout looked a lot messier.",
      "It looked like running on empty for too long and then making decisions I knew weren't helping. Trying to feel better quickly. Trying to feel anything besides overwhelmed.",
      "Trying to get through another hard day without really stopping long enough to ask what the cost was becoming.",
      "## When it turns destructive",
      "And over time that kind of burnout can turn destructive.",
      "You stop taking care of yourself. You avoid things. You make choices that feel good for five minutes and harder for five months.",
      "You tell yourself you'll fix it later.",
      "You push through because people need you.",
      "And eventually you wake up and realize \u201Cpushing through\u201D has turned into survival mode — and survival mode has been driving for a while.",
      "That was hard to admit.",
      "Especially when you care deeply about your family. Especially when you're trying to be dependable. Especially when the people you love need so much from you and you feel like you should be able to carry it.",
      "## What helped",
      "Therapy helped me name some things I had spent a long time trying to outrun.",
      "Self-care stopped feeling optional. It stopped being \u201Cnice if I can find the time.\u201D",
      "It became part of staying functional. Part of staying present. Part of staying me.",
      "## And then, painting",
      "And oddly enough\u2026 painting helped too.",
      "Sitting down with a miniature or a figure gave me something simple and honest to focus on.",
      "No fixing everything. No solving every problem. No carrying the whole weight of the week.",
      "Just the next brushstroke. The next layer.",
      "The reminder that ugly middle stages are normal. That progress doesn't always look dramatic. That patience matters. That rebuilding takes time. That you can start where you are.",
      "## The next right thing",
      "If you're burned out and things feel heavier than they should\u2026 if you've been coping in ways you wish you weren't\u2026 if you feel like you've drifted farther from yourself than you meant to \u2014",
      "You are not alone.",
      "You don't have to fix everything today. You don't have to become a different person overnight.",
      "Sometimes the next right thing is smaller than you think.",
      "Drink some water. Answer one email. Sit outside for five minutes. Paint one small thing. Take one honest breath. Ask for help.",
      "Then do the next thing after that.",
      "That counts. More than you know.",
      "~~signoff",
    ],
    tags: ["self-care", "caregiving", "burnout"],
    placeholder: "essay · wet palette, half-finished mini",
  },
];

// "On the desk" — Diana and Hank.
const NOW_PROJECTS = [
  {
    id: "hank",
    title: "Hank the Ranger",
    cat: "1:6 figure · Toon Studios",
    desc: "My first real go at a 1:6 figure, painting straight onto the model with no test piece. He's coming along nicely — still need a brown wash on the waist armor, some spots left on the base, and his right forearm, bow, and quiver still to paint.",
    pct: 60,
    eta: "No deadline · my first real 1:6",
    stages: ["print", "clean", "assemble", "primer", "base coats", "shade", "highlight", "details", "varnish"],
    current: 6,
    pile: ["brown wash on waist armor", "forearm, bow & quiver", "finish base"],
    placeholder: "now · hank wip",
    image: "assets/gallery/hank-wip-web.jpg",
  },
  {
    id: "diana",
    title: "Diana the Acrobat",
    cat: "1:6 figure · Toon Studios",
    desc: "My first model. Skin, hair, and fur are done; I'm on the gold details now, with her portrait and base left. Turning out well \u2014 going one thin layer at a time.",
    pct: 78,
    eta: "No deadline · learning as I go",
    stages: ["print", "clean", "assemble", "primer", "base coats", "shade", "highlight", "details", "varnish"],
    current: 7,
    pile: ["gold details", "then portrait", "then base"],
    placeholder: "now · diana wip",
    image: "assets/gallery/diana-web.jpg",
  },
];

const SOCIALS = [
  { id: "youtube",   label: "YouTube",   handle: "@brent_the_programmer", desc: "Long-form paint-alongs and quiet workbench sessions.", url: "https://www.youtube.com/channel/UC0nUK7GE2y4qYskGsXiTh9g" },
  { id: "instagram", label: "Instagram", handle: "@brent_the_programmer", desc: "Final shots and the occasional WIP.", url: "https://instagram.com/brent_the_programmer" },
  { id: "facebook",  label: "Facebook",  handle: "Brenttheprogrammer",    desc: "Where my family looks at the figures.", url: "https://facebook.com/Brenttheprogrammer" },
  { id: "patreon",   label: "Patreon",   handle: "Brent Stephenson",      desc: "Support the bench — early looks and works in progress.", url: "https://www.patreon.com/c/BrentStephenson" },
  { id: "coffee",    label: "Buy Me a Coffee", handle: "brent_the_programmer", desc: "A one-off thank-you, if a piece or a post helped your day.", url: "https://buymeacoffee.com/brent_the_programmer" },
  { id: "discord",   label: "Discord",    handle: "the bench",             desc: "A quiet little server — paint talk, WIPs, and good company.", url: "https://discord.gg/u7K5Zuvc" },
];

Object.assign(window, { FACTIONS, GALLERY, POSTS, NOW_PROJECTS, SOCIALS });
